alter table Text drop constraint FK2gx70g1n7fjas2np5of3efc78
alter table Word drop constraint FKlsi5pkxfy1vklotljlannahul
drop table if exists person cascade
drop table if exists Text cascade
drop table if exists Word cascade
alter table Text drop constraint FK2gx70g1n7fjas2np5of3efc78
alter table Word drop constraint FKlsi5pkxfy1vklotljlannahul
drop table if exists person cascade
drop table if exists Text cascade
drop table if exists Word cascade
alter table Text drop constraint FK2gx70g1n7fjas2np5of3efc78
alter table Word drop constraint FKlsi5pkxfy1vklotljlannahul
drop table if exists person cascade
drop table if exists Text cascade
drop table if exists Word cascade
alter table Text drop constraint FK2gx70g1n7fjas2np5of3efc78
alter table Word drop constraint FKlsi5pkxfy1vklotljlannahul
drop table if exists person cascade
drop table if exists Text cascade
drop table if exists Word cascade
alter table Text drop constraint FK2gx70g1n7fjas2np5of3efc78
alter table Word drop constraint FKlsi5pkxfy1vklotljlannahul
drop table if exists person cascade
drop table if exists Text cascade
drop table if exists Word cascade
alter table Text drop constraint FK2gx70g1n7fjas2np5of3efc78
alter table Word drop constraint FKlsi5pkxfy1vklotljlannahul
drop table if exists person cascade
drop table if exists Text cascade
drop table if exists Word cascade
alter table Text drop constraint FK2gx70g1n7fjas2np5of3efc78
alter table Word drop constraint FKlsi5pkxfy1vklotljlannahul
drop table if exists person cascade
drop table if exists Text cascade
drop table if exists Word cascade
alter table Text drop constraint FK2gx70g1n7fjas2np5of3efc78
alter table Word drop constraint FKlsi5pkxfy1vklotljlannahul
drop table if exists person cascade
drop table if exists Text cascade
drop table if exists Word cascade
alter table Text drop constraint FK2gx70g1n7fjas2np5of3efc78
alter table Word drop constraint FKlsi5pkxfy1vklotljlannahul
drop table if exists person cascade
drop table if exists Text cascade
drop table if exists Word cascade
alter table Text drop constraint FK2gx70g1n7fjas2np5of3efc78
alter table Word drop constraint FKlsi5pkxfy1vklotljlannahul
drop table if exists person cascade
drop table if exists Text cascade
drop table if exists Word cascade
alter table Text drop constraint FK2gx70g1n7fjas2np5of3efc78
alter table Word drop constraint FKlsi5pkxfy1vklotljlannahul
drop table if exists person cascade
drop table if exists Text cascade
drop table if exists Word cascade
alter table Text drop constraint FK2gx70g1n7fjas2np5of3efc78
alter table Word drop constraint FKlsi5pkxfy1vklotljlannahul
drop table if exists person cascade
drop table if exists Text cascade
drop table if exists Word cascade
alter table Text drop constraint FK2gx70g1n7fjas2np5of3efc78
alter table Word drop constraint FKlsi5pkxfy1vklotljlannahul
drop table if exists person cascade
drop table if exists Text cascade
drop table if exists Word cascade
alter table Text drop constraint FK2gx70g1n7fjas2np5of3efc78
alter table Word drop constraint FKlsi5pkxfy1vklotljlannahul
drop table if exists person cascade
drop table if exists Text cascade
drop table if exists Word cascade
alter table Text drop constraint FK2gx70g1n7fjas2np5of3efc78
alter table Word drop constraint FKlsi5pkxfy1vklotljlannahul
drop table if exists person cascade
drop table if exists Text cascade
drop table if exists Word cascade
alter table Text drop constraint FK2gx70g1n7fjas2np5of3efc78
alter table Word drop constraint FKlsi5pkxfy1vklotljlannahul
drop table if exists person cascade
drop table if exists Text cascade
drop table if exists Word cascade
alter table Text drop constraint FK2gx70g1n7fjas2np5of3efc78
alter table Word drop constraint FKlsi5pkxfy1vklotljlannahul
drop table if exists person cascade
drop table if exists Text cascade
drop table if exists Word cascade
